### ISSUE TITLE
Latest dev build crashes after opening boot.py

### ISSUE THREAD

**Issue by tttsetsy** [BurningInfern0/ProgressCLI95#22]
It crashes with this error:
Traceback (most recent call last):
  File "C:\Users\пк\Downloads\reg\ProgressCLI95-BurningInfern0-0.2.2b-dev1\boot.py", line 152, in <module>
    boot()
  File "C:\Users\пк\Downloads\reg\ProgressCLI95-BurningInfern0-0.2.2b-dev1\boot.py", line 98, in boot
    ninefivebadge = calculateBadge(ninefive, system95.pro95)
AttributeError: module 'system95' has no attribute 'pro95'

**Comment by BurningInfern0** [comment]
please do not use the dev build yet, it is still in development and will be merged with main when completed
